- name: setup hosts
  hosts: all
  connection: local
  become: true
  tasks:
    - name: Install netstat and ifconfig and update the cache
      apt:
        name: net-tools
        state: latest
        update_cache: yes
    - name: Install build-essential
      apt:
        name: build-essential
        state: latest
    - name: "Install Xubuntu Core. (workaround: Ansible's apt module does not support ^)"
      shell: "apt -qq -y install xubuntu-core"
    - name: "Verify Xubuntu Core is correctly installed"
      apt:
        pkg: "xubuntu-core*"
        state: latest
    - name: "Disable IPv6: modify conf file & disable blanking screen on incactivy"
      lineinfile:
        dest=/etc/default/grub
        regex="GRUB_CMDLINE_LINUX_DEFAULT=\"\""
        line="GRUB_CMDLINE_LINUX_DEFAULT=\"ipv6.disable=1 consoleblank=0\""
        backup=yes
    - name: "Disable IPv6: enact change"
      shell:
        update-grub
    - name: Remove ufw  
      apt:
        name: ufw
        state: absent
    - name: Install Iptables  
      apt:
        name: iptables-persistent
        state: latest
    - name: Create Iptables rule file for IPV4
      copy:
        dest: /etc/iptables/rules.v4
        mode: 0600
        owner: root
        group: root
        src: rules.v4
    - name: Create Iptables rule file for IPV6 (blocks all)
      copy:
        dest: /etc/iptables/rules.v6
        mode: 0600
        owner: root
        group: root
        src: rules.v6
    - name: Create Iptables rule file for debug (allows all)
      copy:
        dest: /etc/iptables/rules.allow_all
        mode: 0600
        owner: root
        group: root
        src: rules.allow_all
    - name: "Disable CUPS"
      ansible.builtin.systemd:
        name: cups
        enabled: no
    - name: "autologin: create empty conf file"
      file:
        path: "/etc/lightdm/lightdm.conf.d/70-autologin.conf"
        state: touch
    - name: "autologin: Insert lines"
      blockinfile:
        path: "/etc/lightdm/lightdm.conf.d/70-autologin.conf"
        block:  |
          [SeatDefaults]
          autologin-user={{nonRootUser}}
    - name: "Remove un-needed folder ~/Public"
      file:
        path: "/home/{{nonRootUser}}/Public/"
        state: absent
    - name: "Remove un-needed folder ~/Music"
      file:
        path: "/home/{{nonRootUser}}/Music/"
        state: absent
    - name: "Remove un-needed folder ~/Documents"
      file:
        path: "/home/{{nonRootUser}}/Documents/"
        state: absent
    - name: "Remove un-needed folder ~/Videos"
      file:
        path: "/home/{{nonRootUser}}/Videos/"
        state: absent
    - name: "Remove un-needed folder ~/Templates"
      file:
        path: "/home/{{nonRootUser}}/Templates/"
        state: absent
    - name: "Enable Network Manager: check if 20.04 file exists"
      stat:
        path: /etc/netplan/00-installer-config.yaml
      register: netplan_config_2004
    - name: "Enable Network Manager 20.04: set NM as renderer"
      lineinfile:
        path: /etc/netplan/00-installer-config.yaml
        insertafter: "network:" 
        line: "  renderer: NetworkManager"
        firstmatch: yes
        state: present  
        when: netplan_config_2004.stat.exists
    - name: "Enable Network Manager: check if 24.04 file exists"
      stat:
        path: /etc/netplan/50-cloud-init.yaml
      register: netplan_config_2004
    - name: "Enable Network Manager 24.04: set NM as renderer"
      lineinfile:
        path: /etc/netplan/50-cloud-init.yaml
        insertafter: "network:" 
        line: "  renderer: NetworkManager"
        firstmatch: yes
        state: present  
        when: netplan_config_2004.stat.exists
    - name: "Enable Network Manager: re-configure netplan 1"
      shell:
        "netplan generate"    
    - name: "Enable Network Manager: re-configure netplan 2"
      shell:
        "netplan apply"
    - name: "Disable the networkd-wait-online service"
      service:
        name:    systemd-networkd-wait-online
        enabled: no
        state:   stopped
    - name: "Disable screen saver"
      become: false
      xfconf:
        channel: "xfce4-screensaver"
        property: "/saver/enabled"
        value_type: "bool"
        value: false
    - name: "Disable lockscreen by the power manager"
      become: false
      xfconf:
        channel: 'xfce4-power-manager'
        property: '/xfce4-power-manager/lock-screen-suspend-hibernate'
        value_type: "bool"
        value: false
    - name: "Disable controlling of the display by the power manager"
      become: false
      xfconf:
        channel: 'xfce4-power-manager'
        property: '/xfce4-power-manager/dpms-enabled'
        value_type: "bool"
        value: false
    - name: "Disable banking the display after no activity"
      become: false
      xfconf:
        channel: 'xfce4-power-manager'
        property: '/xfce4-power-manager/blank-on-ac'
        value_type: "int"
        value: 0
